### PR TITLE
Add Overclock setting inside x86.c

### PR DESCRIPTION
**Pull request by Spidy123222**

### CODE REVIEW

**Comment by QcSamuel** [comment]
hi could you please provide a xemu build with the overclock setting i want to test it to see if the slowdown i get is just xemu or the emulated xbox not keeping up with the 60fps patch im using for conker thanks

**Comment by Spidy123222** [comment]
> hi could you please provide a xemu build with the overclock setting i want to test it to see if the slowdown i get is just xemu or the emulated xbox not keeping up with the 60fps patch im using for conker thanks

It's in GitHub actions

**Comment by QcSamuel** [comment]
> > hi could you please provide a xemu build with the overclock setting i want to test it to see if the slowdown i get is just xemu or the emulated xbox not keeping up with the 60fps patch im using for conker thanks
> 
> It's in GitHub actions

expired

**Comment by Spidy123222** [comment]
> > > hi could you please provide a xemu build with the overclock setting i want to test it to see if the slowdown i get is just xemu or the emulated xbox not keeping up with the 60fps patch im using for conker thanks
> 
> > 
> 
> > It's in GitHub actions
> 
> 
> 
> expired

I updated the branch. You can try now.

**Comment by QcSamuel** [comment]
> > > > hi could you please provide a xemu build with the overclock setting i want to test it to see if the slowdown i get is just xemu or the emulated xbox not keeping up with the 60fps patch im using for conker thanks
> > 
> > 
> > > 
> > 
> > 
> > > It's in GitHub actions
> > 
> > 
> > expired
> 
> I updated the branch. You can try now.

thank you, yeah i tried the oveclock with conker and its a xemu performance problem or conker is really hard on the gpu right now

**Pull request merged**
